
POST http://localhost:8000/temperatures
Content-Type: application/json

{
  "temperature": 1,
  "timestamp": "2022-12-31T09:06:57.973Z"
}

###

POST http://localhost:8000/temperatures
Content-Type: application/json

{
  "temperature": -2.1
}
